# Generated by Django 4.2.5 on 2023-09-30 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emailSender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='doj',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
